# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrackInterpolator
                                 A QGIS plugin
 This plugin geolocates data using GPS tracks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-29
        copyright            : (C) 2021 by Nick
        email                : nickb@uvic.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrackInterpolator class from file TrackInterpolator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .track_interpolator import TrackInterpolator
    return TrackInterpolator(iface)
